apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        {{ if .Values.namespace }}
        image: {{ .Values.namespace }}/{{ .Values.name }}:{{ default latest .Values.tag }}
        {{ else }}
        image: {{ .Values.name }}:{{ default latest .Values.tag }}
        {{ end }}
