apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-transporter
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: url-shortener-api
data:
  TRANSPORTER: nats://nats.nats.svc.cluster.local:4222
