charts:
  - cert-manager
  - external-dns
  - ingress-nginx
  - kubernetes-reflector
  - nats
  - url-shortener-microservices
repoUrl: <current (this) repo url, dynamically populated by argocd during cluster bootstrapping>
