deployment:
  name: url-shortener-microservices
  tag: f919763bdc6e792017c12dd6aad6daeea08a2697
  namespace: aliasrahil
  envFrom:
    - secretRef:
        name: db-credentials
    - configMapRef:
        name: nats-transporter
